# Generated by Django 4.1 on 2022-09-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_todolistitem_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolistitem',
            options={'ordering': ['created']},
        ),
    ]
